/* The problem:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

var result = 0;
var fibSequence = [ ];
fibSequence.push (1);
fibSequence.push (1);
for (i=2; i<=32; i++){
  fibSequence.push(fibSequence[i-1] + fibSequence [i-2]);
}
console.log (fibSequence);
for (i=1; i<=32; i++){
  if (fibSequence[i]%2==0){
    result +=fibSequence[i];
  }
}
console.log(result);
